---
# tasks file for git-server
- name: Ensure git is installed (RedHat).
  package:
    name: "{{ git_packages }}"
    state: present
    enablerepo: "{{ git_enablerepo | default(omit, true) }}"
  when:
    - not git_install_from_source
    - ansible_os_family == 'RedHat'

- name: Ensure git is installed (Suse).
  apt:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source
    - ansible_os_family == 'Suse'
- import_tasks: install-from-source.yml
